spring.application.name=springboot-ChatGPT

openapi.api.url=https://openrouter.ai/api/v1/chat/completions
openapi.api.model=meta-llama/llama-3-8b-instruct
openapi.api.key=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
